### PR TITLE
add random-user-profile-generator

### PR DESCRIPTION
**Pull request by ahmadkhairul**
## Description

random API for generating dummy user profile data

## Screenshot

Optional

<hr>
Checklist

- [ ] API used in this PR was not used in just-calling-random-api before.
- [ ] API used in this PR is Public or I have permission to use it.
- [ ] My contribution is working.
- [ ] My contribution doesn't expose any API keys.
- [ ] My changes don't generate any new warnings.
- [ ] My changes don't affect any work done by other developers.

To tick a box, replace `[ ]` with `[x]`.

### CODE REVIEW

**Comment by akimabs** [comment]
hi @ahmadkhairul great contribution, but your PR has been conflct.
please pull code from master and i will merge your PR. thanks!

**Comment by ahmadkhairul** [comment]
ok please wait @akimabs

**Comment by ahmadkhairul** [comment]
@akimabs it's should be fixed by now

**Comment by akimabs** [comment]
finally! thanks for this contribute man @ahmadkhairul 🤟

**Pull request merged**
